using System;
using System.Collections.Generic;
using Godot;

public static partial class Loc
{
	private const string DEFAULT_LANGUAGE = "english";
	private const string LOCALIZATION_PATH = "res://resources/localization/";

	private static Dictionary<string, string> _strings = new Dictionary<string, string>();
	private static bool _subscribedToCVar;

	public static Action OnLanguageChanged;

	public static void Init(string language)
	{
		if (!_subscribedToCVar)
		{
			CVars.language.OnChanged += (cvar) =>
			{
				Init(cvar.GetString());
				OnLanguageChanged?.Invoke();
			};
			_subscribedToCVar = true;
		}

		if (string.IsNullOrEmpty(language))
		{
			language = DEFAULT_LANGUAGE;
		}

		_strings.Clear();

		string dir = LOCALIZATION_PATH + language;
		if (!DirAccess.DirExistsAbsolute(dir))
		{
			GD.PrintErr($"Localization folder not found: {dir}");
			return;
		}

		List<string> files = new List<string>();
		CollectTsvFiles(dir, files);
		// Sorted so a duplicate key resolves the same way every run.
		files.Sort(StringComparer.Ordinal);
		for (int i = 0; i < files.Count; i++)
		{
			LoadFile(files[i]);
		}
	}

	// Every .tsv under the language folder, subfolders included — `dialogue/`
	// holds the conversation text generated by tools/conversation_import, and
	// the key namespace stays flat across all of them.
	static void CollectTsvFiles(string dir, List<string> files)
	{
		using var da = DirAccess.Open(dir);
		if (da == null)
		{
			GD.PrintErr($"Failed to open localization folder: {dir}");
			return;
		}
		foreach (string name in da.GetFiles())
		{
			if (name.EndsWith(".tsv", StringComparison.Ordinal))
			{
				files.Add(dir + "/" + name);
			}
		}
		foreach (string sub in da.GetDirectories())
		{
			CollectTsvFiles(dir + "/" + sub, files);
		}
	}

	static void LoadFile(string path)
	{
		using var file = FileAccess.Open(path, FileAccess.ModeFlags.Read);
		if (file == null)
		{
			GD.PrintErr($"Failed to open localization file: {path}");
			return;
		}

		// Skip header row
		if (!file.EofReached())
		{
			file.GetLine();
		}

		while (!file.EofReached())
		{
			string line = file.GetLine();
			if (string.IsNullOrEmpty(line))
			{
				continue;
			}

			int wsIndex = line.IndexOfAny(new[] { ' ', '\t' });
			if (wsIndex < 0)
			{
				continue;
			}

			string key = line.Substring(0, wsIndex);
			string value = line.Substring(wsIndex).TrimStart();
			if (_strings.ContainsKey(key))
			{
				GD.PushError($"Duplicate localization key '{key}' in {path} - keys are one flat namespace across every .tsv in the language folder.");
			}
			_strings[key] = value;
		}
	}

	public static string Get(Keys key)
	{
		string keyName = key.ToString();
		if (_strings.TryGetValue(keyName, out string value))
		{
			return value;
		}

		return $"MISSING:{keyName}";
	}

	// String-keyed lookup for content-driven sites that store loc keys as
	// authored data (e.g. MobData.dialogueLocKeys). The typed `Keys` enum is
	// preferred at code call sites because the build-time generator catches
	// typos; this overload is the escape hatch when the key only exists as
	// a piece of authored data.
	public static string Get(StringName key)
	{
		if (key == default)
		{
			return "";
		}
		string keyName = key.ToString();
		if (_strings.TryGetValue(keyName, out string value))
		{
			return value;
		}
		return $"MISSING:{keyName}";
	}

	public static string Format(Keys key, params object[] args)
	{
		return Substitute(Get(key), args);
	}

	// String-keyed Format for content-driven sites that store loc keys as
	// authored data (e.g. QuestData.textKey's "%0" placeholder). Escape hatch
	// mirroring Get(StringName) — prefer the typed Keys overload at code sites.
	public static string Format(StringName key, params object[] args)
	{
		return Substitute(Get(key), args);
	}

	static string Substitute(string text, object[] args)
	{
		for (int i = 0; i < args.Length; i++)
		{
			text = text.Replace($"%{i}", args[i]?.ToString() ?? "");
		}
		return text;
	}
}
