// Auto-generated by LocGenerator — do not edit
public static partial class Loc
{
	public enum Keys
	{
		villager_greeting,
		villager_dialogue_1,
		villager_dialogue_2,
		villager_resp_tell_more,
		villager_resp_beard,
		villager_resp_trade,
		villager_nothing_more,
		villager_thanks,
		villager_lets_do_it,
		weapon_name_prefix,
		weapon_name_suffix,
		status_duration_until,
		time_of_day_sunrise,
		time_of_day_noon,
		time_of_day_sunset,
		time_of_day_midnight,
		danger_nearby,
		too_hurt_to_rest,
		not_enough_health_to_revive
	}
}
