using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;

class Program
{
	static int Main(string[] args)
	{
		string repoRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
		string inputDir = Path.Combine(repoRoot, "resources", "localization", "english");
		string outputPath = Path.Combine(repoRoot, "scripts", "localization", "LocKeys.g.cs");

		if (args.Length >= 2)
		{
			inputDir = args[0];
			outputPath = args[1];
		}

		if (!Directory.Exists(inputDir))
		{
			Console.Error.WriteLine($"Input folder not found: {inputDir}");
			return 1;
		}

		// Files directly in the language folder are hand-authored and generate
		// the typed Keys enum. Subfolders (dialogue/, written by
		// tools/conversation_import) are loaded at runtime and span-checked
		// here, but stay out of the enum: nothing in code can name a
		// conversation line, they are only ever reached by StringName from a
		// ConversationData.
		var enumFiles = new List<string>(Directory.GetFiles(inputDir, "*.tsv", SearchOption.TopDirectoryOnly));
		var allFiles = new List<string>(Directory.GetFiles(inputDir, "*.tsv", SearchOption.AllDirectories));
		enumFiles.Sort(StringComparer.Ordinal);
		allFiles.Sort(StringComparer.Ordinal);

		var keys = new List<string>();
		var seen = new HashSet<string>(StringComparer.Ordinal);
		int markupWarnings = 0;
		foreach (string file in allFiles)
		{
			bool inEnum = enumFiles.Contains(file);
			foreach (string raw in ReadLines(file))
			{
				string line = raw.Trim();
				if (string.IsNullOrEmpty(line))
				{
					continue;
				}

				int wsIndex = line.IndexOfAny(new[] { ' ', '\t' });
				string key = wsIndex >= 0 ? line.Substring(0, wsIndex) : line;
				if (!seen.Add(key))
				{
					// The whole language folder is one flat key namespace, so a
					// repeat means one of the two strings silently wins at runtime.
					Console.Error.WriteLine($"LocGenerator: duplicate key '{key}' in {Path.GetFileName(file)}.");
					markupWarnings++;
				}
				else if (inEnum)
				{
					keys.Add(key);
				}
				if (wsIndex >= 0)
				{
					ValidateLanguageSpans(key, line.Substring(wsIndex + 1), KnownLanguageIds(inputDir), ref markupWarnings);
				}
			}
		}
		if (markupWarnings > 0)
		{
			// Warn, never fail: half-authored strings must not block a build or
			// a playtest (same rule as ValidateScriptVars in hike.csproj).
			Console.Error.WriteLine($"LocGenerator: {markupWarnings} warning(s) - see above.");
		}

		using var writer = new StreamWriter(outputPath);
		writer.WriteLine("// Auto-generated by LocGenerator — do not edit");
		writer.WriteLine("public static partial class Loc");
		writer.WriteLine("{");
		writer.WriteLine("\tpublic enum Keys");
		writer.WriteLine("\t{");
		for (int i = 0; i < keys.Count; i++)
		{
			writer.Write($"\t\t{keys[i]}");
			if (i < keys.Count - 1)
			{
				writer.Write(",");
			}

			writer.WriteLine();
		}

		writer.WriteLine("\t}");
		writer.WriteLine("}");

		Console.WriteLine($"Generated {keys.Count} keys -> {outputPath}");
		return 0;
	}

	// Skips the header row. FileShare.ReadWrite, not File.ReadAllLines: a tsv is
	// routinely open in a spreadsheet while strings are being authored, and that
	// holder's write handle makes the default (FileShare.Read) request fail -
	// which failed the whole build with an unhandled IOException.
	static List<string> ReadLines(string path)
	{
		var lines = new List<string>();
		using (var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
		using (var reader = new StreamReader(stream))
		{
			string line;
			while ((line = reader.ReadLine()) != null)
			{
				lines.Add(line);
			}
		}
		if (lines.Count > 0)
		{
			lines.RemoveAt(0);
		}
		return lines;
	}

	const string TagOpen = "[lang:";
	const string TagClose = "[/lang]";
	// Mirrors LanguageText.CommonId - the reserved span id meaning "no
	// language", so it is never registered as a LanguageData.
	const string CommonId = "common";

	static HashSet<string> _knownLanguageIds;

	// Every LanguageData.id authored anywhere under resources/. Scanned once
	// and cached; a .tres holding one is identified by its script_class
	// header, so the ids move with the data and this tool needs no list of
	// its own.
	static HashSet<string> KnownLanguageIds(string inputDir)
	{
		if (_knownLanguageIds != null)
		{
			return _knownLanguageIds;
		}
		_knownLanguageIds = new HashSet<string>(StringComparer.Ordinal);
		string resourcesDir = Path.GetFullPath(Path.Combine(inputDir, "..", ".."));
		if (!Directory.Exists(resourcesDir))
		{
			return _knownLanguageIds;
		}
		foreach (string path in Directory.EnumerateFiles(resourcesDir, "*.tres", SearchOption.AllDirectories))
		{
			string text;
			try
			{
				text = File.ReadAllText(path);
			}
			catch (IOException)
			{
				continue;
			}
			if (!text.Contains("script_class=\"LanguageData\""))
			{
				continue;
			}
			Match match = Regex.Match(text, "^id = &\"([^\"]*)\"", RegexOptions.Multiline);
			if (match.Success && match.Groups[1].Value.Length > 0)
			{
				_knownLanguageIds.Add(match.Groups[1].Value);
			}
		}
		return _knownLanguageIds;
	}

	// Balance / nesting / unknown-id check for the inline language spans
	// LanguageText parses at display time. Catching it here means an author
	// hears about a typo on the next build instead of the next time that
	// particular line happens to be shown in game.
	static void ValidateLanguageSpans(string key, string value, HashSet<string> knownIds, ref int warnings)
	{
		bool open = false;
		int i = 0;
		while (true)
		{
			int nextOpen = value.IndexOf(TagOpen, i, StringComparison.Ordinal);
			int nextClose = value.IndexOf(TagClose, i, StringComparison.Ordinal);
			if (nextOpen < 0 && nextClose < 0)
			{
				break;
			}
			if (nextClose >= 0 && (nextOpen < 0 || nextClose < nextOpen))
			{
				if (!open)
				{
					Warn(key, $"'{TagClose}' with no open span", ref warnings);
				}
				open = false;
				i = nextClose + TagClose.Length;
				continue;
			}
			int end = value.IndexOf(']', nextOpen + TagOpen.Length);
			if (end < 0)
			{
				Warn(key, $"unterminated '{TagOpen}' tag", ref warnings);
				return;
			}
			if (open)
			{
				Warn(key, $"nested '{TagOpen}' tag - spans do not nest", ref warnings);
			}
			string id = value.Substring(nextOpen + TagOpen.Length, end - nextOpen - TagOpen.Length);
			if (id != CommonId && !knownIds.Contains(id))
			{
				Warn(key, $"unknown language id '{id}' - no LanguageData under resources/ declares it, and it is not '{CommonId}'", ref warnings);
			}
			open = true;
			i = end + 1;
		}
		if (open)
		{
			Warn(key, $"span left open (missing '{TagClose}')", ref warnings);
		}
	}

	static void Warn(string key, string message, ref int warnings)
	{
		Console.Error.WriteLine($"LocGenerator: {key}: {message}.");
		warnings++;
	}
}
