using System;
using System.Collections.Generic;
using System.IO;

class Program
{
	static int Main(string[] args)
	{
		string repoRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
		string inputPath = Path.Combine(repoRoot, "resources", "localization", "english.tsv");
		string outputPath = Path.Combine(repoRoot, "scripts", "localization", "LocKeys.g.cs");

		if (args.Length >= 2)
		{
			inputPath = args[0];
			outputPath = args[1];
		}

		if (!File.Exists(inputPath))
		{
			Console.Error.WriteLine($"Input file not found: {inputPath}");
			return 1;
		}

		var keys = new List<string>();
		string[] lines = File.ReadAllLines(inputPath);
		for (int i = 1; i < lines.Length; i++)
		{
			string line = lines[i].Trim();
			if (string.IsNullOrEmpty(line))
			{
				continue;
			}

			int wsIndex = line.IndexOfAny(new[] { ' ', '\t' });
			string key = wsIndex >= 0 ? line.Substring(0, wsIndex) : line;
			keys.Add(key);
		}

		using var writer = new StreamWriter(outputPath);
		writer.WriteLine("// Auto-generated by LocGenerator — do not edit");
		writer.WriteLine("public static partial class Loc");
		writer.WriteLine("{");
		writer.WriteLine("\tpublic enum Keys");
		writer.WriteLine("\t{");
		for (int i = 0; i < keys.Count; i++)
		{
			writer.Write($"\t\t{keys[i]}");
			if (i < keys.Count - 1)
			{
				writer.Write(",");
			}

			writer.WriteLine();
		}

		writer.WriteLine("\t}");
		writer.WriteLine("}");

		Console.WriteLine($"Generated {keys.Count} keys -> {outputPath}");
		return 0;
	}
}
